openapi: "3.0.0"
info:
  description: "OpenLattice API"
  version: "0.0.1"
  title: "OpenLattice API"
  termsOfService: "http://api.openlattice.com/terms/"
  contact:
    email: "support@openlattice.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
    - url: "https://api.openlattice.com"
      description: "Production OpenLattice API"
    - url: "https://api.staging.openlattice.com"
      description: "Staging OpenLattice API"
    - url: "http://localhost:8080"
      description: "Local OpenLattice API"

paths:

  ###############
  ## EDM API"s ##
  ###############

  # edm

  /datastore/edm/:
    $ref: ./EDM/EDM.yaml#/EDM
  /datastore/diff/:
    $ref: ./EDM/EDM.yaml#/EDMdiff
  /datastore/version/:
    $ref: ./EDM/EDM.yaml#/EDMversion

  # entity sets

  /datastore/edm/entity/set/{entitySetId}:
    $ref: ./EDM/entityset.yaml#/entitySetId
  /datastore/edm/ids/entity/set/{entitySetName}:
    $ref: ./EDM/entityset.yaml#/entitySetName
  /datastore/edm/entity/set:
    $ref: ./EDM/entityset.yaml#/entitySet
  /datastore/edm/entity/set/{entitySetId}/property/type:
    $ref: ./EDM/entityset.yaml#/entitySetPropertyTypes
  /datastore/edm/entity/set/{entitySetId}/property/type/{propertyTypeId}/:
    $ref: ./EDM/entityset.yaml#/entitySetPropertyType

  #entity types

  /datastore/edm/entity/type/{entityTypeId}:
    $ref: ./EDM/entitytype.yaml#/entityTypeId
  /datastore/edm/ids/entity/type/{namespace}/{name}:
    $ref: ./EDM/entitytype.yaml#/entityTypeName
  /datastore/edm/entity/type/{entityTypeId}/{propertyTypeId}:
    $ref: ./EDM/entitytype.yaml#/entityTypePropertyType
  /datastore/edm/entity/type/{entityTypeId}/{propertyTypeId}/force:
    $ref: ./EDM/entitytype.yaml#/entityTypePropertyTypeForce
  /datastore/edm/entity/type/:
    $ref: ./EDM/entitytype.yaml#/entityTypes
  /datastore/edm/association/type/:
    $ref: ./EDM/entitytype.yaml#/associationTypes
  /datastore/edm/entity/type/{entityTypeId}/property/type:
    $ref: ./EDM/entitytype.yaml#/entityTypePropertyOrder
  /datastore/edm/entity/type/{entityTypeId}/hierarchy:
    $ref: ./EDM/entitytype.yaml#/entityTypeHierarchy

  # property Types

  /datastore/edm/property/type/{propertyTypeId}:
    $ref: ./EDM/propertytype.yaml#/propertyTypeId
  /datastore/edm/property/type/{propertyTypeId}/force:
    $ref: ./EDM/propertytype.yaml#/propertyTypeForce
  /datastore/edm/ids/property/type/{namespace}/{name}:
    $ref: ./EDM/propertytype.yaml#/propertyTypeName
  /datastore/edm/property/type/:
    $ref: ./EDM/propertytype.yaml#/propertyTypes
  /datastore/edm/property/type/namespace/{namespace}:
    $ref: ./EDM/propertytype.yaml#/propertyTypeNamespace

  # association types

  /datastore/edm/association/type/{associationTypeId}:
    $ref: ./EDM/associationtype.yaml#/associationTypeId
  /datastore/edm/association/type/{associationTypeId}/detailed:
    $ref: ./EDM/associationtype.yaml#/associationTypeDetails
  /datastore/edm/association/type/{associationTypeId}/available:
    $ref: ./EDM/associationtype.yaml#/associationTypeAvailable
  /datastore/edm/association/type/{associationTypeId}/dst/{entityTypeId}:
    $ref: ./EDM/associationtype.yaml#/associationTypeDst
  /datastore/edm/association/type/{associationTypeId}/src/{entityTypeId}:
    $ref: ./EDM/associationtype.yaml#/associationTypeSrc

  # summary

  /datastore/edm/summary:
    $ref: ./EDM/summary.yaml#/summary
  /datastore/edm/summary/{propertyTypeId}:
    $ref: ./EDM/summary.yaml#/summaryProperty

  #######################
  ## PERMISSIONS API"s ##
  #######################

  /datastore/principals/users/search/email/"{emailAddress}":
    $ref: ./permissions/permissions.yaml#/searchEmail
  /datastore/permissions:
    $ref: ./permissions/permissions.yaml#/permissions


tags:
- name: edm
  description: Entity Data Model API"s
  externalDocs:
    description: OpenLattice help pages
    url: https://help.openlattice.com/
- name: permissions
  description: Permissions API"s
  externalDocs:
    description: OpenLattice help pages
    url: https://help.openlattice.com/
externalDocs:
  description: "Find out more about OpenLattice"
  url: "https://openlattice.com/"
