openapi: "3.0.0"
info:
  description: "OpenLattice API"
  version: "0.0.1"
  title: "OpenLattice API"
  termsOfService: "http://api.openlattice.com/terms/"
  contact:
    email: "support@openlattice.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
    - url: "https://api.openlattice.com"
      description: "Production OpenLattice API"
    - url: "https://api.staging.openlattice.com"
      description: "Staging OpenLattice API"
    - url: "http://localhost:8080"
      description: "Local OpenLattice API"

paths:

  ###############
  ## EDM API"s ##
  ###############

  # edm

  /datastore/edm/:
    $ref: ./definitions/EDM/EDM.yaml#/EDM
  /datastore/edm/diff/:
    $ref: ./definitions/EDM/EDM.yaml#/EDMdiff
  /datastore/edm/version/:
    $ref: ./definitions/EDM/EDM.yaml#/EDMversion

  # entity sets

  /datastore/edm/entity/set/{entitySetId}:
    $ref: ./definitions/EDM/entityset.yaml#/entitySetId
  /datastore/edm/ids/entity/set/{entitySetName}:
    $ref: ./definitions/EDM/entityset.yaml#/entitySetName
  /datastore/edm/entity/set:
    $ref: ./definitions/EDM/entityset.yaml#/entitySet
  /datastore/edm/entity/set/{entitySetId}/property/type:
    $ref: ./definitions/EDM/entityset.yaml#/entitySetPropertyTypes
  /datastore/edm/entity/set/{entitySetId}/property/type/{propertyTypeId}/:
    $ref: ./definitions/EDM/entityset.yaml#/entitySetPropertyType

  #entity types

  /datastore/edm/entity/type/{entityTypeId}:
    $ref: ./definitions/EDM/entitytype.yaml#/entityTypeId
  /datastore/edm/ids/entity/type/{namespace}/{name}:
    $ref: ./definitions/EDM/entitytype.yaml#/entityTypeName
  /datastore/edm/entity/type/{entityTypeId}/{propertyTypeId}:
    $ref: ./definitions/EDM/entitytype.yaml#/entityTypePropertyType
  /datastore/edm/entity/type/{entityTypeId}/{propertyTypeId}/force:
    $ref: ./definitions/EDM/entitytype.yaml#/entityTypePropertyTypeForce
  /datastore/edm/entity/type/:
    $ref: ./definitions/EDM/entitytype.yaml#/entityTypes
  /datastore/edm/association/type/:
    $ref: ./definitions/EDM/entitytype.yaml#/associationTypes
  /datastore/edm/entity/type/{entityTypeId}/property/type:
    $ref: ./definitions/EDM/entitytype.yaml#/entityTypePropertyOrder
  /datastore/edm/entity/type/{entityTypeId}/hierarchy:
    $ref: ./definitions/EDM/entitytype.yaml#/entityTypeHierarchy

  # property Types

  /datastore/edm/property/type/{propertyTypeId}:
    $ref: ./definitions/EDM/propertytype.yaml#/propertyTypeId
  /datastore/edm/property/type/{propertyTypeId}/force:
    $ref: ./definitions/EDM/propertytype.yaml#/propertyTypeForce
  /datastore/edm/ids/property/type/{namespace}/{name}:
    $ref: ./definitions/EDM/propertytype.yaml#/propertyTypeName
  /datastore/edm/property/type/:
    $ref: ./definitions/EDM/propertytype.yaml#/propertyTypes
  /datastore/edm/property/type/namespace/{namespace}:
    $ref: ./definitions/EDM/propertytype.yaml#/propertyTypeNamespace

  # association types

  /datastore/edm/association/type/{associationTypeId}:
    $ref: ./definitions/EDM/associationtype.yaml#/associationTypeId
  /datastore/edm/association/type/{associationTypeId}/detailed:
    $ref: ./definitions/EDM/associationtype.yaml#/associationTypeDetails
  /datastore/edm/association/type/{associationTypeId}/available:
    $ref: ./definitions/EDM/associationtype.yaml#/associationTypeAvailable
  /datastore/edm/association/type/{associationTypeId}/dst/{entityTypeId}:
    $ref: ./definitions/EDM/associationtype.yaml#/associationTypeDst
  /datastore/edm/association/type/{associationTypeId}/src/{entityTypeId}:
    $ref: ./definitions/EDM/associationtype.yaml#/associationTypeSrc

  # summary

  /datastore/edm/summary:
    $ref: ./definitions/EDM/summary.yaml#/summary
  /datastore/edm/summary/{propertyTypeId}:
    $ref: ./definitions/EDM/summary.yaml#/summaryProperty

  # schema

  /datastore/edm/schema/{namespace}/{name}:
    $ref: ./definitions/EDM/schema.yaml#/schemaFqn
  /datastore/edm/schema:
    $ref: ./definitions/EDM/schema.yaml#/schema
  /datastore/edm/schema/{namespace}:
    $ref: ./definitions/EDM/schema.yaml#/schemaNamespace

  ################
  ## DATA API"s ##
  ################

  /datastore/data/set/{entitySetId}:
    $ref: ./definitions/data/data.yaml#/entitySetId
  /datastore/data/set/{entitySetId}/entities:
    $ref: ./definitions/data/data.yaml#/entities
  /datastore/data/{entitySetId}/count:
    $ref: ./definitions/data/data.yaml#/count

  ##################
  ## SEARCH API"s ##
  ##################

  /datastore/search/{entitySetId}/{entityKeyId}:
    $ref: ./definitions/search/search.yaml#/entityKey
  /datastore/search/{entitySetId}/neighbors/advanced:
    $ref: ./definitions/search/search.yaml#/filteredSearch

  #####################
  ## DIRECTORY API"s ##
  #####################

  /datastore/principals/users/search/email/"{emailAddress}":
    $ref: ./definitions/directory/principal.yaml#/searchEmail

  #########################
  ## AUTHORIZATION API"s ##
  #########################

  /datastore/permissions:
    $ref: ./definitions/authorization/permissions.yaml#/permissions

components:
  securitySchemes:
    openlattice_auth:
      type: apiKey
      in: header
      name: Authorization


tags:
- name: edm
  description: Entity Data Model API"s
- name: permissions
  description: Permissions API"s
- name: directory
  description: Directory API"s
- name: data
  description: Data API's
externalDocs:
  description: "Find out more about OpenLattice"
  url: "https://openlattice.com/"
